services:
  app:
    build: .
    volumes:
      - .:/app
    environment:
      - MAIL_SERVER_HOST=${MAIL_SERVER_HOST}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    command: "node index.js"
    tty: true