services:
  app:
    build: .
    volumes:
      - .:/app
    environment:
      - MAIL_SERVER_HOST=${MAIL_SERVER_HOST}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    tty: true
    dns:
      - "1.0.0.1"
      - "1.1.1.1"