services:
  app:
    build: .
    volumes:
      - .:/app
    tty: true
    environment:
      MAIL_SERVER_HOST: ${MAIL_SERVER_HOST}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}